#!/bin/bash

set -e
#set -x

IMAGE=test

# docker build . -t test && docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY --volume="$HOME/.Xauthority:/home/build/.Xauthority:rw" --net=host test xsbug

install_all() {
    for FILE in $(find $1 -type f -executable)
    do
        echo Installing $(basename $FILE)
        TARGET=/install/$(basename $FILE)
        cat >$TARGET <<EOF
#!/bin/sh
docker run -it --rm -v \$HOME:/home/build -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY --net=host $IMAGE $FILE
EOF
    chmod 770 $TARGET
    done    
}

install_all ${MODDABLE}/build/bin/lin/release
