#!/bin/bash

set -e

CONTAINER=moddable-sdk
TARGET_DIR=$1

if [ -z $TARGET_DIR ]
then
    echo "use: start <target-dir>"
    exit 1
fi

executables() {
    find ${MODDABLE}/build/bin/lin/release -type f -executable
}

    for FILE in $(executables)
    do
        echo Installing $(basename $FILE)
        TARGET=$TARGET_DIR/$(basename $FILE)
        cat >$TARGET <<EOF
#!/bin/sh
set -e
podman exec -it --workdir=\$PWD $CONTAINER $FILE \$@
EOF
    chmod 770 $TARGET
    done    


uninstall() {
    for FILE in $(executables)
    do
        echo Uninstalling $(basename $FILE)
        TARGET=$TARGET_DIR/$(basename $FILE)
        rm $TARGET
    done    
}

trap uninstall SIGINT
bash
uninstall
